 Random forest is basically a group of trees. It is a bagging based technique.. (Bootstrapped agregration).
 Randomly data select kore sampling kore.
 In random forest we use bagging technique and set all models as decision trees

In [2]:
import numpy as np
def bootstrapping(x,y,n_bootstrap):
    n = len(x)
    idx = np.arange(n)
    x_boot = np.zeros((n_bootstrap,n))
    y_boot = np.zeros((n_bootstrap,n))
    for i in range(n_bootstrap):
        idx_boot = np.random.choice(idx,n)
        x_boot[i] = x[idx_boot]
        y_boot[i] = y[idx_boot]
    return x_boot,y_boot


In [8]:
def max_feature(x):
    # x is a 2D array
    n= x.shape[1]
    n_feature = int(np.sqrt(n))
    idx = np.random.choice(n,n_feature,replace=False)
    return x[:,idx]



In [14]:
x= np.random.rand(10,5)
print(x)

[[0.34883741 0.64971337 0.95835191 0.9797035  0.99472773]
 [0.41757515 0.02449087 0.35888475 0.64051809 0.9098737 ]
 [0.80316947 0.21712047 0.55189457 0.47199713 0.99762934]
 [0.42612514 0.42570571 0.73303505 0.43675033 0.51954131]
 [0.30321354 0.61776877 0.38055158 0.50477374 0.4421958 ]
 [0.81733503 0.09372389 0.24036633 0.49282911 0.22140315]
 [0.24550488 0.84197026 0.86681165 0.13334307 0.74962455]
 [0.50863516 0.54438624 0.97601577 0.6869505  0.58081087]
 [0.39727269 0.97450125 0.60969878 0.41514343 0.79655125]
 [0.80772974 0.36548297 0.23945231 0.84467841 0.04024946]]
